<a href="https://colab.research.google.com/github/shekkari1999/PyTorch_learning/blob/main/pytorch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

print(torch.__version__)

2.3.1+cu121


In [ ]:
#Tensors

scaler = torch.tensor(7)
print(scaler,'\n')
print('dimensions are ',scaler.ndim,'\n')
print('shape is',scaler.shape,'\n')

tensor(7) 

dimensions are  0 

shape is torch.Size([]) 



In [ ]:
## vector

## No of square brakets are dimensions

vector = torch.tensor([7,7])
print(vector,'\n')
print('dimensions are ',vector.ndim,'\n')
print('shape is',vector.shape,'\n')

tensor([7, 7]) 

dimensions are  1 

shape is torch.Size([2]) 



In [ ]:
## Matrix

MATRIX = torch.tensor([[7,7],
                       [8,8]])

print(MATRIX,'\n')
print('dimensions are', MATRIX.ndim,'\n')
print('shape is', MATRIX.shape)
print("")
print(MATRIX[1][1].item())
print(MATRIX[0][1].item())
print(MATRIX[0][0].item())
print(MATRIX[1][0].item())

tensor([[7, 7],
        [8, 8]]) 

dimensions are 2 

shape is torch.Size([2, 2])

8
7
7
8


In [ ]:
#TENSOR

TENSOR = torch.tensor([[
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[11,22,33],
                        [44,55,66],
                        [77,88,99]]
                       ])

print(TENSOR,'\n')
print('dimensions are',TENSOR.ndim,'\n')
print('dimensions are',TENSOR.shape,'\n')

#Getting elements

print(TENSOR[1][1][1].item()) # second matrix, second row, second column
print(TENSOR[0][2][0].item()) # First Matrix, 3rd row, 1st column

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99]]]) 

dimensions are 3 

dimensions are torch.Size([2, 3, 3]) 

55
7


In [ ]:
## Random Tensors

# Random tensors are imp because many NN start to learn from random numbers
# lets create (3, 4) tensor

random_tensor = torch.rand(4,3,4)
random_tensor


tensor([[[0.9785, 0.8554, 0.8722, 0.7993],
         [0.6936, 0.0548, 0.3953, 0.5536],
         [0.8847, 0.4980, 0.4359, 0.4949]],

        [[0.9346, 0.0501, 0.6103, 0.3017],
         [0.8422, 0.2199, 0.6856, 0.9169],
         [0.2792, 0.3247, 0.2633, 0.5330]],

        [[0.7692, 0.9020, 0.0506, 0.2946],
         [0.0152, 0.5994, 0.1311, 0.7879],
         [0.4052, 0.4925, 0.5755, 0.0850]],

        [[0.9752, 0.3774, 0.9395, 0.2642],
         [0.1561, 0.2932, 0.2983, 0.0453],
         [0.4726, 0.5965, 0.7980, 0.9692]]])

In [ ]:
# create image size tensor
image_tensor = torch.rand(3,224,224)

print('shape is', image_tensor.shape,'\n')
print('Dimensions are',image_tensor.ndim)

shape is torch.Size([3, 224, 224]) 

Dimensions are 3


In [ ]:
## Create tensors of Zeroes and Ones

## Used for Masking

zeros = torch.zeros(3,4)
print(zeros,'\n')

print(zeros.dtype) # default ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 

torch.float32


In [ ]:
# create tensors within particular range

range_tensor = torch.arange(start = 0,end = 30,step = 2)

range_tensor


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
# creating tensors-like

range_tensor_like = torch.zeros_like(input = range_tensor)

range_tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
## can we create a range tensor of size (3,4,4)

import torch

# Create a tensor with numbers from 0 to 10
tensor = torch.linspace(0, 50, steps=9).view(1, 3, 3)
print(tensor)

tensor([[[ 0.0000,  6.2500, 12.5000],
         [18.7500, 25.0000, 31.2500],
         [37.5000, 43.7500, 50.0000]]])


In [ ]:
 ## Tensor Data types

 # Precision in computing

float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype = None,
                            device = None,
                            requires_grad = False)

float_tensor

tensor([3., 6., 9.])

In [ ]:
float_16 = float_tensor.type(dtype = torch.half)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# 16 multiplied by 32

float_16 * float_tensor

tensor([ 9., 36., 81.])

In [ ]:
# Matrix Multiplication

tensor_A = torch.tensor([1,2,3])
tensor_B = torch.tensor([1,4,5])

print(torch.matmul(tensor_A,tensor_B),'\n')

## Element wise Multiplication

print(tensor_A * tensor_B)

tensor(24) 

tensor([ 1,  8, 15])


In [ ]:
# Aggregations / pytorch methods in tensors

print(min(tensor_A))
print(sum(tensor_A))
print(tensor_A.sum())
print(tensor_A.type(torch.float32).mean())

## So there are Multiple ways

#tensor_A.mean()
#torch.mean(tensor_A.type(torch.float32))

tensor(1)
tensor(6)
tensor(6)
tensor(2.)


tensor(2.)

In [ ]:
# Reshaping, viewing and Stacking, squeezing and unsqeezing

x = torch.arange(1,10)
print(x,'\n')
print(x.shape)

## reshaping

x_reshaped = x.reshape(9,1)
print('\n(9,1) reshaped is \n\n',x_reshaped)
print('\n',x_reshaped.shape)
x_reshaped[5].item()


x_reshaped_2 = x.reshape(3,3)
print('\n(9,1) reshaped is \n\n',x_reshaped_2)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) 

torch.Size([9])

(9,1) reshaped is 

 tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

 torch.Size([9, 1])

(9,1) reshaped is 

 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# View of a tensor shares memory as original tensor

z = x.view(1,9)
print(z)

print(z[0][0].item())

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
1


In [ ]:
# Stacking

x_stacked = torch.stack([x,x,x,x],dim = 1)

print(x_stacked)
print(x_stacked.shape)
print(x_stacked.dim())

print(x_stacked[2][3].item())

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])
torch.Size([9, 4])
2
3


In [ ]:
# squeez

x_squeezed = x.squeeze()

print(x_squeezed)
print(x_squeezed.shape)
print(x.shape)

z_squeezed = z.squeeze()
print(z.shape)
print(z_squeezed.shape)
print(z_squeezed[0].item())

## Just put unsqueeze in place of squeeze for unsqueeze

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
torch.Size([9])
torch.Size([1, 9])
torch.Size([9])
1


In [ ]:
## research about torch.permute

# Permute is mostly used with images

In [ ]:
# indexing (selecting data from tensors)

x = x.reshape(1,3,3)
print(x,'\n')

print(x[0][0][0])
print('Give me all from the first matrix \nconsider all rows, second index column\n')
print(x[:,0:3,2])

print('Give me one number from the first matrix \nconsider first row, second index column\n')
print(x[0,0,2])

print('give me (5,6)')
print(x[:,1,1:3])

# last digit of slices are excluded

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 

tensor(1)
Give me all from the first matrix 
consider all rows, second index column

tensor([[3, 6, 9]])
Give me one number from the first matrix 
consider first row, second index column

tensor(3)
give me (5,6)
tensor([[5, 6]])


In [ ]:
## Pytorch and numpy

import torch
import numpy as np

array = np.arange(1,8)

## numpy --> tensor
tensor = torch.from_numpy(array)
print(array, tensor)
print(array.dtype,tensor.dtype)

## tensor --> numpy

array = tensor.numpy()

[1 2 3 4 5 6 7] tensor([1, 2, 3, 4, 5, 6, 7])
int64 torch.int64


In [ ]:
# reproducability

#just like seed parameter

torch.manual_seed(42)
torch.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [ ]:
## Accessing GPU

'''
1. Google colab
2. Own GPU
3. Azure, AWS, GCP

'''

In [ ]:
# setting up device agnostic code

'''
1. Numpy only works on CPU

'''

'\n1. Numpy only works on CPU\n\n'

In [ ]:
# Excercises